builds:
  - binary: denoken
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: denoken
    homepage: https://github.com/sandricoprovo/homebrew-denoken
    tap:
      owner: sandricoproco
      name: homebrew-denoken
    commit_author:
      name: sprovo
      email: sprovo@outlook.com

checksum:
  name_template: 'checksums.txt'
